version: "3.8"
services:
  db:
    image: mysql:latest
    container_name: my-mysql
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
    ports:
      - "3307:3306"
    volumes:
      - mysql-volume:/var/lib/mysql
volumes:
  mysql-volume:
    driver: local