version: '3.8'
services: 
  app: 
    build: .
    command: yarn dev
    ports: 
      - '3000:3000'
    volumes: 
      - .:/app
    depends_on:
      - "db"
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
    volumes:
      - db:/var/lib/mysql
    ports: 
      - '3307:$DB_DOCK_PORT'
volumes:
  db:
